server:
  servlet:
    context-path: /api

spring:
  application:
    name: user-service
  main:
    banner-mode: off
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1
